version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/data/conf:/etc/mysql
      - $PWD/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nzqloves225
    ports:
      - "3306:3306"
    expose: 
      - 3306

