version: '2'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/data:/data
    command: redis-server /data/redis.conf

  #redis-slave:
    #image: redis:latest
    #command: redis-server --slaveof redis-master 6379
    #links:
      #- redis-master

  sentinel:
    image: redis:latest
    container_name: sentinel
    links:
      - redis
    ports:
      - 26379:26379
    expose:
      - 26379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/data:/data
    command: redis-server /data/sentinel.conf --sentinel
